[workspace]
members = ["associated","creating-structs","defining-structs", "elements", "enum-types", "enums", "enums-vectors", "manipulating", "match-enum", "option-enum", "strings", "vectors", "vectors-values"]
